CREATE SEQUENCE IF NOT EXISTS ORDER_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE ORDERS
(
    ID            bigint not null DEFAULT NEXT VALUE FOR ORDER_ID_SEQUENCE PRIMARY KEY,
    CREATION      timestamp(6),
    RESTAURANT_ID bigint not null,
    CONSTRAINT ORDER_RESTAURANT_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS ORDER_ITEM_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE ORDER_ITEMS
(
    ID       bigint not null DEFAULT NEXT VALUE FOR ORDER_ITEM_ID_SEQUENCE PRIMARY KEY,
    DISH_ID  bigint not null,
    ORDER_ID bigint not null,
    CONSTRAINT ORDER_ITEM_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE
);