INSERT INTO RESTAURANTS (NAME, ADDRESS)
VALUES ('Ромашка', 'Улица Пушкина');
INSERT INTO RESTAURANTS (NAME, ADDRESS)
VALUES ('Клевер', 'Улица Лермонтова');

INSERT INTO DISHES (ID, NAME, DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES (1, 'Булка', 'Вкусная', 15, 1);
INSERT INTO DISHES (ID, NAME, DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES (2, 'Коржик', 'Молочный', 22, 1);
INSERT INTO DISHES (ID, NAME, DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES (3, 'Пицца Маргарита', 'Неаполитанская', 77.7, 2);
INSERT INTO DISHES (ID, NAME, DESCRIPTION, PRICE, RESTAURANT_ID)
VALUES (4, 'Пицца Пепперони', 'Римская', 92.3, 2);